language: php
php:
  - 5.5
  - 5.4
  - hhvm
install:
  - cp composer.json.dist composer.json
  - composer install
  - cd src/bin
  - chmod +x server.sh
  - ./server.sh &
  - cd ../../
script: phpunit
