language: php
php:
  - 5.5
  - 5.4
  - hhvm
install:
  - rm composer.json
  - cp composer.json.dist composer.json
  - composer install
  - cd src/bin
  - chmod +x server.sh
  - ./server.sh &
  - cd ../../
  - mkdir -p build/logs
script: phpunit
after_script:
  - php vendor/bin/coveralls
